alter table dbo.REF_PERSON add column PERSON_GUARANTOR_RELATION nvarchar(50) null
alter table dbo.REF_PERSON alter column CREATED_DATE datetime null
alter table dbo.M_ZONE alter column CREATED_DATE datetime null
alter table dbo.T_LOAN_SURVEY add column SURVEY_RECEIVED_BY nvarchar(50) null
alter table dbo.T_LOAN_SURVEY add column SURVEY_PROCESS_BY nvarchar(50) null
alter table dbo.T_INSTALLMENT add column INSTALLMENT_PAID numeric(18, 5) null

alter table [dbo].[M_EMPLOYEE] add column ADDRESS_ID nvarchar(50) null

ALTER TABLE [dbo].[M_EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_M_EMPLOYEE_REF_ADDRESS] FOREIGN KEY([ADDRESS_ID])
REFERENCES [dbo].[REF_ADDRESS] ([ADDRESS_ID])
GO

ALTER TABLE [dbo].[M_EMPLOYEE] CHECK CONSTRAINT [FK_M_EMPLOYEE_REF_ADDRESS]

alter table dbo.T_LOAN alter column LOAN_IS_SALESMAN_KNOWN_CUST nvarchar(50) null

USE DB_SIMK_WMTI
GO

SP_RENAME 'M_COMMISSION.CUSTOMER_STATUS' , 'COMMISSION_STATUS' , 'COLUMN'
GO

SP_RENAME 'M_COMMISSION.CUSTOMER_DESC' , 'COMMISSION_DESC' , 'COLUMN'
GO

ALTER TABLE [dbo].[M_COMMISSION_DET] ADD DETAIL_LOW_TARGET NUMERIC(18, 5) NULL
GO

ALTER TABLE [dbo].[M_COMMISSION_DET] ADD DETAIL_HIGH_TARGET NUMERIC(18, 5) NULL
GO

ALTER TABLE [dbo].[M_COMMISSION_DET] ADD DETAIL_CUSTOMER_NUMBER INT NULL
GO

ALTER TABLE [dbo].[M_COMMISSION_DET] ADD DETAIL_TRANSPORT_ALLOWANCE NUMERIC(18, 5) NULL
GO

ALTER TABLE [dbo].[M_COMMISSION_DET] ADD DETAIL_INCENTIVE NUMERIC(18, 5) NULL
GO

ALTER TABLE [dbo].[M_COMMISSION_DET] ADD DETAIL_INCENTIVE_SURVEY_ACC NUMERIC(18, 5) NULL
GO

ALTER TABLE [dbo].[M_COMMISSION_DET] ADD DETAIL_INCENTIVE_SURVEY_ONLY NUMERIC(18, 5) NULL
GO

ALTER TABLE dbo.T_INSTALLMENT ADD INSTALLMENT_FACTUR_NO nvarchar(50) NULL
GO


CREATE TABLE [dbo].[T_LOAN_FEEDBACK](
	[LOAN_FEEDBACK_ID] [nvarchar](50) NOT NULL,
	[LOAN_ID] [nvarchar](50) NULL,
	[LOAN_FEEDBACK_TYPE] [nvarchar](50) NULL,
	[LOAN_FEEDBACK_DESC] [nvarchar](max) NULL,
	[LOAN_FEEDBACK_BY] [nvarchar](50) NULL,
	[LOAN_FEEDBACK_STATUS] [nvarchar](50) NULL,
	[DATA_STATUS] [nvarchar](50) NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[ROW_VERSION] [timestamp] NULL,
 CONSTRAINT [PK_T_LOAN_FEEDBACK] PRIMARY KEY CLUSTERED 
(
	[LOAN_FEEDBACK_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[T_LOAN_FEEDBACK]  WITH CHECK ADD  CONSTRAINT [FK_T_LOAN_FEEDBACK_T_LOAN] FOREIGN KEY([LOAN_ID])
REFERENCES [dbo].[T_LOAN] ([LOAN_ID])
GO

ALTER TABLE [dbo].[T_LOAN_FEEDBACK] CHECK CONSTRAINT [FK_T_LOAN_FEEDBACK_T_LOAN]
GO